# This is a basic workflow to help you get started with Actions

name: Update CI

# Controls when the action will run. 
on:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created, edited]
  push:
    branches:
      - main
    paths:
      - main.py


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  GITHUB_NAME: JIN
  GITHUB_EMAIL: jinjiting2690@gmail.com
  GITHUB_TOKEN: ${{ secrets.GEN_README }}
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          node-version: 3.6

      - name: Configure node cache
        uses: actions/cache@v2
        id: node-cache
        with:
          path: venv
          key: pip-1-PyGithub
          restore-keys: |
            pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m venv venv
          source venv/bin/activate
          pip install PyGithub
        if: steps.pip-cache.outputs.cache-hit != 'true'

      - name: Generate README
        run: |
          source venv/bin/activate
          python main.py ${{ env.GITHUB_TOKEN }} ${{ github.repository }} --issue_numbe '${{ github.event.issue.number }}'
        
      - name: Push README
        uses: github-actions-x/commit@v2.6
        with:
          # github-token: ${{ env.GITHUB_TOKEN }}
          commit-message: "chore: build"
          files: README.md
          rebase: 'true'
          name: ${{ env.GITHUB_NAME }}
          email: ${{ env.GITHUB_EMAIL }}